<?php
declare(strict_types=1);

$config_path = __DIR__ . '/data/config.php';

// Already configured — redirect to app
if (file_exists($config_path)) {
    header('Location: index.php');
    exit;
}

$errors = [];
$success = false;

if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $key = trim($_POST['usda_key'] ?? '');

    // Skip — write a config with no key and continue to app
    if (isset($_POST['skip'])) {
        if (!is_dir(__DIR__ . '/data')) mkdir(__DIR__ . '/data', 0755, true);
        $php = "<?php\nif (!defined('DIET_APP')) { http_response_code(403); exit; }\n// Auto-generated by setup — no USDA API key configured\n";
        file_put_contents($config_path, $php);
        header('Location: index.php');
        exit;
    }

    if (!$key) {
        $errors[] = 'API key is required.';
    } else {
        // Verify the key works before saving
        $test_url = 'https://api.nal.usda.gov/fdc/v1/foods/search?query=apple&pageSize=1&api_key=' . urlencode($key);
        $ctx = stream_context_create(['http' => ['timeout' => 8, 'ignore_errors' => true]]);
        $result = @file_get_contents($test_url, false, $ctx);
        $http_status = $http_response_header[0] ?? '';

        if ($result === false || str_contains($http_status, '403') || str_contains($http_status, '401')) {
            $errors[] = 'Could not verify API key — please check it and try again.';
        } else {
            // Ensure data/ dir exists
            if (!is_dir(__DIR__ . '/data')) {
                mkdir(__DIR__ . '/data', 0755, true);
            }
            $php = "<?php\nif (!defined('DIET_APP')) { http_response_code(403); exit; }\n// Auto-generated by setup — do not edit manually\ndefine('USDA_API_KEY', " . var_export($key, true) . ");\n";
            if (file_put_contents($config_path, $php) === false) {
                $errors[] = 'Could not write config file. Check that the data/ directory is writable.';
            } else {
                header('Location: index.php');
                exit;
            }
        }
    }
}
?>
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Setup — Diet Tracker</title>
<style>
*, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; background: #f8f9fa; color: #212529; font-size: 16px; display: flex; align-items: center; justify-content: center; min-height: 100vh; padding: 16px; }
.card { background: #fff; border-radius: 10px; box-shadow: 0 1px 3px rgba(0,0,0,.08); padding: 28px 24px; width: 100%; max-width: 440px; }
h1 { font-size: 1.2rem; font-weight: 700; color: #2d6a4f; margin-bottom: 6px; }
p { font-size: .9rem; color: #6c757d; margin-bottom: 20px; line-height: 1.5; }
label { display: block; font-size: .85rem; font-weight: 500; margin-bottom: 4px; color: #6c757d; }
input { width: 100%; padding: 10px 12px; border: 1px solid #dee2e6; border-radius: 8px; font-size: 1rem; font-family: inherit; margin-bottom: 16px; }
input:focus { outline: none; border-color: #52b788; box-shadow: 0 0 0 3px rgba(82,183,136,.15); }
button { width: 100%; padding: 12px; background: #2d6a4f; color: #fff; border: none; border-radius: 8px; font-size: 1rem; font-weight: 600; cursor: pointer; }
button:hover { background: #1b4332; }
.alert { padding: 10px 14px; border-radius: 8px; margin-bottom: 16px; font-size: .9rem; background: #ffe5e5; color: #a00; }
a { color: #2d6a4f; }
</style>
</head>
<body>
<div class="card">
    <h1>Diet Tracker Setup</h1>
    <p>A USDA FoodData Central API key enables food nutrition lookups. You can skip this now and add the key later in Settings. Follow these steps to get your free key:</p>
    <ol style="font-size:.9rem;color:#6c757d;line-height:1.8;margin:-8px 0 20px 18px">
        <li>Go to <a href="https://fdc.nal.usda.gov/api-guide.html" target="_blank">fdc.nal.usda.gov/api-guide.html</a></li>
        <li>Click <strong>Sign up / Request an API Key</strong></li>
        <li>Enter your name and email address</li>
        <li>Check your email — your key arrives instantly</li>
        <li>Paste it below</li>
    </ol>

    <?php if ($errors): ?>
        <div class="alert"><?= implode('<br>', array_map('htmlspecialchars', $errors)) ?></div>
    <?php endif; ?>

    <form method="post">
        <label for="usda_key">USDA FoodData Central API Key</label>
        <input type="text" id="usda_key" name="usda_key" placeholder="Paste your API key here"
               value="<?= htmlspecialchars($_POST['usda_key'] ?? '') ?>" autofocus>
        <button type="submit">Verify &amp; Save</button>
    </form>
    <form method="post" style="margin-top:10px">
        <button type="submit" name="skip" value="1"
                style="background:none;border:none;color:#6c757d;font-size:.9rem;cursor:pointer;text-decoration:underline;padding:0;width:auto">
            Skip for now
        </button>
    </form>
</div>
</body>
</html>
