<?php
// settings.php — Per-person profile, daily goals, named meals, USDA API key, and data links.
declare(strict_types=1);
session_start();
require_once __DIR__ . '/db.php';
require_once __DIR__ . '/layout.php';

$db = get_db();
$errors = [];
$success = '';

$people = $db->query('SELECT * FROM people ORDER BY id')->fetchAll();
$active = get_active_person();

if ($_SERVER['REQUEST_METHOD'] === 'POST' && isset($_POST['action'])) {
    csrf_verify();
    $action = $_POST['action'];

    if ($action === 'save_person') {
        $pid     = (int)($_POST['person_id'] ?? 0);
        $name    = trim($_POST['name'] ?? '');
        $fiber   = (float)($_POST['goal_fiber_g'] ?? 0);
        $protein = (float)($_POST['goal_protein_g'] ?? 0);
        $produce = (float)($_POST['goal_produce_servings'] ?? 0);
        $notes   = trim($_POST['notes'] ?? '');
        $color_raw = trim($_POST['header_color'] ?? '');
        $header_color = preg_match('/^#[0-9a-fA-F]{6}$/', $color_raw) ? $color_raw : '#2d6a4f';

        if (!$name) { $errors[] = 'Name is required.'; }

        if (empty($errors)) {
            if ($pid) {
                $db->prepare("UPDATE people SET name=?, goal_fiber_g=?, goal_protein_g=?, goal_produce_servings=?, notes=?, header_color=? WHERE id=?")
                   ->execute([$name, $fiber, $protein, $produce, $notes ?: null, $header_color, $pid]);
                $success = 'Saved.';
                // Re-fetch so the page reflects the update
                $active = get_active_person();
            } else {
                $db->prepare("INSERT INTO people (name, goal_fiber_g, goal_protein_g, goal_produce_servings, notes, header_color) VALUES (?,?,?,?,?,?)")
                   ->execute([$name, $fiber, $protein, $produce, $notes ?: null, $header_color]);
                $new_id = (int)$db->lastInsertId();
                $_SESSION['person_id'] = $new_id;
                // Redirect to the new person's settings with their u param
                header('Location: settings.php?u=' . $new_id . '&added=1');
                exit;
            }
            $people = $db->query('SELECT * FROM people ORDER BY id')->fetchAll();
        }
    }

    if ($action === 'save_api_key') {
        $key = trim($_POST['usda_key'] ?? '');
        $config_path = __DIR__ . '/data/config.php';
        if ($key) {
            // Verify before saving
            $test_url = 'https://api.nal.usda.gov/fdc/v1/foods/search?query=apple&pageSize=1&api_key=' . urlencode($key);
            $ctx = stream_context_create(['http' => ['timeout' => 8, 'ignore_errors' => true]]);
            $result = @file_get_contents($test_url, false, $ctx);
            $http_status = $http_response_header[0] ?? '';
            if ($result === false || str_contains($http_status, '403') || str_contains($http_status, '401')) {
                $errors[] = 'Could not verify API key — please check it and try again.';
            } else {
                $php = "<?php\nif (!defined('DIET_APP')) { http_response_code(403); exit; }\n// Auto-generated by setup — do not edit manually\ndefine('USDA_API_KEY', " . var_export($key, true) . ");\n";
                if (file_put_contents($config_path, $php) === false) {
                    $errors[] = 'Could not write config file. Check that the data/ directory is writable.';
                } else {
                    header('Location: settings.php' . u_qs() . '&api_saved=1');
                    exit;
                }
            }
        } else {
            // Clear the key — rewrite config without it
            $php = "<?php\nif (!defined('DIET_APP')) { http_response_code(403); exit; }\n// Auto-generated by setup — no USDA API key configured\n";
            file_put_contents($config_path, $php);
            header('Location: settings.php' . u_qs() . '&api_saved=1');
            exit;
        }
    }

    if ($action === 'delete_template') {
        $tid = (int)($_POST['template_id'] ?? 0);
        $db->prepare('DELETE FROM meal_templates WHERE id = ?')->execute([$tid]);
        header('Location: settings.php' . u_qs() . '#templates');
        exit;
    }
}

// Which person's goals are we editing?
$edit_pid = isset($_GET['edit']) ? (int)$_GET['edit'] : ($active['id'] ?? null);
// ?new=1 means adding a new person
$new_person = isset($_GET['new']);
$edit_person = null;
if (!$new_person) {
    foreach ($people as $p) {
        if ($p['id'] == $edit_pid) { $edit_person = $p; break; }
    }
    if (!$edit_person && !empty($people)) { $edit_person = $people[0]; }
}

$templates = $db->query("
    SELECT mt.id, mt.name, COUNT(mti.id) AS item_count
    FROM meal_templates mt
    LEFT JOIN meal_template_items mti ON mti.template_id = mt.id
    GROUP BY mt.id ORDER BY mt.name
")->fetchAll();

page_header('Settings', 'settings');
?>

<?php if ($errors): ?>
    <div class="alert alert-error"><?= implode('<br>', array_map('htmlspecialchars', $errors)) ?></div>
<?php endif; ?>
<?php if ($success): ?>
    <div class="alert alert-success"><?= htmlspecialchars($success) ?></div>
<?php endif; ?>
<?php if (isset($_GET['added'])): ?>
    <div class="alert alert-success">Person added. Bookmark this page URL to come back as this person.</div>
<?php endif; ?>

<!-- Person selector tabs -->
<?php if (count($people) > 0): ?>
<div class="card">
    <h2>People &amp; Goals</h2>
    <div style="display:flex;gap:8px;flex-wrap:wrap;margin-bottom:16px">
        <?php foreach ($people as $p): ?>
            <a href="settings.php?edit=<?= $p['id'] ?><?= u_amp() ?>"
               class="btn <?= (!$new_person && $p['id'] == ($edit_person['id'] ?? null)) ? 'btn-primary' : 'btn-secondary' ?> btn-sm">
                <?= htmlspecialchars($p['name']) ?>
            </a>
        <?php endforeach; ?>
        <a href="settings.php?new=1<?= u_amp() ?>"
           class="btn <?= $new_person ? 'btn-primary' : 'btn-secondary' ?> btn-sm">+ Add person</a>
    </div>

    <form method="post">
        <input type="hidden" name="action" value="save_person"><?= csrf_field() ?>
        <input type="hidden" name="person_id" value="<?= $new_person ? 0 : ($edit_person['id'] ?? 0) ?>">

        <div class="form-group">
            <label for="person-name">Name</label>
            <input type="text" id="person-name" name="name"
                   value="<?= htmlspecialchars($new_person ? '' : ($edit_person['name'] ?? '')) ?>"
                   required <?= $new_person ? 'autofocus' : '' ?>>
        </div>

        <div style="display:flex;align-items:baseline;justify-content:space-between;margin-bottom:10px">
            <div style="font-size:.85rem;color:var(--muted);font-weight:600">Daily Goals</div>
            <a href="https://www.nal.usda.gov/human-nutrition-and-food-safety/dri-calculator" target="_blank" rel="noopener" style="font-size:.78rem">DRI Calculator</a>
        </div>
        <div class="form-row">
            <div class="form-group">
                <label for="goal-fiber">Fiber (g)</label>
                <input type="number" id="goal-fiber" name="goal_fiber_g"
                       value="<?= $new_person ? 0 : ($edit_person['goal_fiber_g'] ?? 0) ?>"
                       step="1" min="0">
            </div>
            <div class="form-group">
                <label for="goal-protein">Protein (g)</label>
                <input type="number" id="goal-protein" name="goal_protein_g"
                       value="<?= $new_person ? 0 : ($edit_person['goal_protein_g'] ?? 0) ?>"
                       step="1" min="0">
            </div>
            <div class="form-group">
                <label for="goal-produce">Produce (srv)</label>
                <input type="number" id="goal-produce" name="goal_produce_servings"
                       value="<?= $new_person ? 0 : ($edit_person['goal_produce_servings'] ?? 0) ?>"
                       step="0.5" min="0">
            </div>
        </div>
        <div class="form-group">
            <label for="person-notes">Notes</label>
            <textarea id="person-notes" name="notes" rows="2"><?= htmlspecialchars($new_person ? '' : ($edit_person['notes'] ?? '')) ?></textarea>
        </div>
        <div class="form-group">
            <label for="header-color">Header color</label>
            <div style="display:flex;align-items:center;gap:10px">
                <input type="color" id="header-color" name="header_color"
                       value="<?= htmlspecialchars($new_person ? '#2d6a4f' : ($edit_person['header_color'] ?? '#2d6a4f')) ?>"
                       style="width:48px;height:36px;padding:2px;border:1px solid var(--border);border-radius:6px;cursor:pointer;background:none">
                <button type="button" class="btn btn-secondary btn-sm"
                        onclick="document.getElementById('header-color').value='#2d6a4f'">Reset to default</button>
            </div>
        </div>
        <button type="submit" class="btn btn-primary btn-block">
            <?= $new_person ? 'Create Person' : 'Save Profile Info' ?>
        </button>
    </form>

    <?php if (!$new_person && $edit_person): ?>
    <div style="margin-top:16px;padding-top:16px;border-top:1px solid var(--border)">
        <div style="font-size:.85rem;color:var(--muted);margin-bottom:6px;font-weight:500">Bookmarkable URL for <?= htmlspecialchars($edit_person['name']) ?></div>
        <code style="font-size:.8rem;background:var(--bg);padding:6px 10px;border-radius:6px;display:block;word-break:break-all;color:var(--text)">
            <?= htmlspecialchars((isset($_SERVER['HTTPS']) ? 'https' : 'http') . '://' . $_SERVER['HTTP_HOST'] . dirname($_SERVER['PHP_SELF']) . '/index.php?u=' . $edit_person['id']) ?>
        </code>
    </div>
    <?php endif; ?>
</div>
<?php else: ?>
<!-- No people yet -->
<div class="card">
    <h2>Welcome! Set up your profile</h2>
    <form method="post">
        <input type="hidden" name="action" value="save_person"><?= csrf_field() ?>
        <input type="hidden" name="person_id" value="0">
        <div class="form-group">
            <label for="new-person-name">Your name</label>
            <input type="text" id="new-person-name" name="name" required autofocus>
        </div>
        <div style="font-size:.85rem;color:var(--muted);font-weight:600;margin-bottom:10px">Daily Goals</div>
        <div class="form-row">
            <div class="form-group">
                <label for="new-goal-fiber">Fiber (g)</label>
                <input type="number" id="new-goal-fiber" name="goal_fiber_g" value="0" step="1" min="0">
            </div>
            <div class="form-group">
                <label for="new-goal-protein">Protein (g)</label>
                <input type="number" id="new-goal-protein" name="goal_protein_g" value="0" step="1" min="0">
            </div>
            <div class="form-group">
                <label for="new-goal-produce">Produce (srv)</label>
                <input type="number" id="new-goal-produce" name="goal_produce_servings" value="0" step="0.5" min="0">
            </div>
        </div>
        <button type="submit" class="btn btn-primary btn-block">Get Started</button>
    </form>
</div>
<?php endif; ?>

<!-- Named meals -->
<div class="card" id="templates">
    <h2>Named Meals</h2>
    <?php if (empty($templates)): ?>
        <p class="empty">No named meals saved yet.</p>
    <?php else: ?>
        <?php foreach ($templates as $t): ?>
            <div class="meal-item">
                <div>
                    <div class="food-name"><?= htmlspecialchars($t['name']) ?></div>
                    <div class="food-meta"><?= $t['item_count'] ?> food<?= $t['item_count'] != 1 ? 's' : '' ?></div>
                </div>
                <form method="post" style="margin:0">
                    <input type="hidden" name="action" value="delete_template"><?= csrf_field() ?>
                    <input type="hidden" name="template_id" value="<?= $t['id'] ?>">
                    <button type="submit" class="btn btn-danger btn-sm"
                            onclick="return confirm('Delete named meal &quot;<?= htmlspecialchars(addslashes($t['name'])) ?>&quot;?')">Delete</button>
                </form>
            </div>
        <?php endforeach; ?>
    <?php endif; ?>
</div>


<?php if (isset($_GET['api_saved'])): ?>
    <div class="alert alert-success">API key settings saved.</div>
<?php endif; ?>

<!-- USDA API key -->
<div class="card">
    <h2>USDA Food Lookup</h2>
    <?php $has_key = defined('USDA_API_KEY') && USDA_API_KEY !== ''; ?>
    <p style="font-size:.85rem;color:var(--muted);margin-bottom:14px;line-height:1.6">
        <?php if ($has_key): ?>
            An API key is configured. Food nutrition lookup from the USDA database is enabled.
            Enter a new key below to replace it, or leave blank and save to remove it.
        <?php else: ?>
            No API key is set. Enter one below to enable food nutrition lookup from the USDA database.
            Get a free key at <a href="https://fdc.nal.usda.gov/api-guide.html" target="_blank">fdc.nal.usda.gov</a>.
        <?php endif; ?>
    </p>
    <form method="post">
        <input type="hidden" name="action" value="save_api_key"><?= csrf_field() ?>
        <div class="form-group">
            <label for="usda-key">USDA FoodData Central API Key</label>
            <input type="text" id="usda-key" name="usda_key"
                   placeholder="<?= $has_key ? 'Enter new key to replace, or leave blank to remove' : 'Paste your API key here' ?>">
        </div>
        <button type="submit" class="btn btn-primary btn-block">Save API Key</button>
    </form>
</div>

<!-- Import / Export -->
<div class="card">
    <h2>Data</h2>
    <div style="display:flex;flex-direction:column;gap:10px">
        <a href="import.php<?= u_qs() ?>" class="btn btn-secondary">Import CSV</a>
        <a href="export.php<?= u_qs() ?>" class="btn btn-secondary">Export all data as CSV</a>
    </div>
</div>

<?php page_footer('settings'); ?>
